const SecretActionTypes = {
  SUBMIT_SECRET_START: 'SUBMIT_SECRET_START',
  SUBMIT_SECRET_SUCCESS: 'SUBMIT_SECRET_SUCCESS',
  SUBMIT_SECRET_FAILURE: 'SUBMIT_SECRET_FAILURE',
  FETCH_SECRETS_START: 'FETCH_SECRETS_START',
  FETCH_SECRETS_SUCCESS: 'FETCH_SECRETS_SUCCESS',
  FETCH_SECRETS_FAILURE: 'FETCH_SECRETS_FAILURE',
}

export default SecretActionTypes;
